image: golang:latest
stages:
  - build

before_script:
  - apt update -y
  - apt install -y protobuf-compiler npm curl
  - curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.25.0/buf-$(uname -s)-$(uname -m)" -o "/usr/local/bin/buf" 
  - chmod +x "/usr/local/bin/buf"
  - make tools

build-all:
  stage: build
  retry: 1
  script:
    - make build-all
    - git diff --exit-code

lint:
  stage: build
  retry: 1
  script:
    - make lint

format:
  stage: build
  retry: 1
  script:
    - make format
    - git diff --exit-code
