name: Test Dependency

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: Build Dependency Test with iscp-rs
        run: |
          cd /tmp
          cargo init --bin dependency-test
          cd dependency-test
          echo -e 'async-trait = "0.1"' >>Cargo.toml
          echo -e 'chrono = "0.4"' >>Cargo.toml
          echo -e 'tokio = { version = "1.21", features = ["rt"] }' >>Cargo.toml
          echo -e 'uuid = "1.2"' >>Cargo.toml
          echo -e 'iscp-rs = { path = "'${GITHUB_WORKSPACE}'" }' >>Cargo.toml
          cp ${GITHUB_WORKSPACE}/examples/upstream.rs src/main.rs
          rustc --version
          cargo --version
          cargo check --verbose
          cargo build --verbose

# publish:

# build-with-crateio
